## Instruct Fine-tuning

В предыдущих семинарах мы в основном фокусировались на какой-то одной задаче - исправление опечаток, выделение сущностей, определение тональности, машинный перевод и т.п. Мы двигались от самых простых моделей к предобученным трансформерам, но подход в целом не менялся - мы брали модель и тренировали её решать нужную задачу, а когда нужно было решить новую задачу мы откладывали старую модель и тренировали новую. 

Одно из главных изменений в NLP в последние несколько лет - это то, что решать разные задачи стало возможно одной общей моделью. Если задуматься, то все к этому шло:

1) Self-supervised предобучение научились более менее стабильно масштабировать на огромные текстовые корпуса, что дало нам модели, в которых уже заложено очень широкое понимание языка
2) трасформеры оказались очень масштабируемой архитектурой, что позволило масштабировать не только данные, но и размер модели; и оказалось, что увеличение размера модели дает нелинейный прирост в качестве
3) При правильных промтах предобученный модели могли решать даже задачи, которые они никогда не видели (zero-shot и in context learning)
4) Fine-tuning предобученных моделей под конкретную задачу требует небольшое количество примеров (сотни или даже десятки)
5) Все возможные NLP задачи стали сводится к генерации текста (классификация - генерация одного токена, исправление опечаток - генерация исправленной последовательности, выделение сущности - генерация именованых сущностей нужного типа, даже генерация кода теперь решается просто генерацией)


Поэтому было вопросом времени, когда кто-то попробует обучить модель решать сразу все нужные задачи и у них получится.

Текущее стандартное решение - дообучить модель на датесете разнообразных инструкций, которые соответствуют нужным задачам, а затем дотренировать новую модель с помощью Reinforcement Learning from Human Feedback (RLHF). Такой подход первым успешно применил OpenAI и результат можно наблюдать в ChatGPT (спойлер: результат очень хороший). Но OpenAI не опубликовал в открытом доступе ни модели, ни код ни подробные технические описания их подхода. Поэтому сейчас болшАя часть исследовательского сообщества в NLP занимается тем, что пытается воспроизвести chatgpt по общем описаниям, которые раскрыл OpenAI. И очень многое уже получилось воспроизвести и буквально с каждым днем такие модели становятся меньше/дешевле и доступнее.

Помимо OpenAI стоит упомянуть еще две статьи (и модели), которые есть в открытом доступе и которые сильно повлияли на движение в сторону общих моделей.

## T5

![](https://1.bp.blogspot.com/-o4oiOExxq1s/Xk26XPC3haI/AAAAAAAAFU8/NBlvOWB84L0PTYy9TzZBaLf6fwPGJTR0QCLcBGAsYHQ/s640/image3.gif)


Первая статья Т5 (Text-To-Text Transfer Transformer, https://arxiv.org/abs/1910.10683, Google Research, конец 2019 года) 
Это очень большая статья, в которой подробно исследовалась унификация различных NLP задач в задачу генерации. А также они попробовали много различных подходов к предобучению (в то время выходило очень много статей, которые как-то меняли self-supervised задачу и они попробовали много разных комбинаций, чтобы получить хорошую модель). В результате у них получилось несколько вариантов модели Т5 и всех их они выложили в открытый доступ. 
Еще в статье они пробовали тюнить модель под разные задачи, но по большей части все еще по отдельности. Если вы прочитаете статью или хотя бы описание fine-tuning экспериментов, то увидите, что на тот момент парадигма (1 модель - 1 задача) еще не изменилась. В своих экспериментах они пробовали тренироваться сразу под несколько задач, но у них было не достаточно много разнообразных задач и в итоге общая модель работала хуже на отдельных задачах, чем специфичные модели.

Но в открытый доступ они выложили в том числе и модели, которые были дообучены на нескольких задачах. Задача в модель передается через префикс (посмотрите на начало примеров выше). Эти модели есть на huggingface, давайте попробуем взять какую-то модель и попробовать сходу решить задачу саммаризации.

In [24]:
# %pip install pandas transformers datasets 'accelerate>=1.1.0'

In [6]:
import pandas as pd
import numpy as np
import torch
import json

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

In [7]:
# MODEL_NAME = 't5-large'
MODEL_NAME = 't5-base'
# MODEL_NAME = 't5-small'

In [8]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, model_max_length=512)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/257 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Возьмем какой-нибудь текст

In [9]:
task_prefix = "summarize: {}"

text = """
Badgers burrowing under rail tracks have halted trains in the northern and southern Netherlands, forcing lengthy cancellations on at least two lines.
All trains were halted Tuesday afternoon on a busy line between the southern cities of Den Bosch and Boxtel after the animals dug into a dike carrying rails. The national railway company said the line would be out of service for at least a week.
The digging means "the rails can subside and then the safety of train traffic can no longer be guaranteed," ProRail, the company that maintains the Dutch rail network said in a statement.
Earlier this month, badgers also burrowed under tracks near the northern village of Molkwerum in Friesland province, knocking a line out of service until next month while workers seek permission to shift the animals.
Badgers are protected animals in the Netherlands, so rail operators have to get permission to move them or disturb their habitat before repairs can begin.
"""

С моделями в huggingface удобнее всего работать через torch, но это не страшно, так как все основные вещи реализованы в transformers и они одинаковые для torch и tf. 

Попробуем сгенерировать саммари

In [10]:
inputs = tokenizer([task_prefix.format(text)], 
                    return_tensors="pt", padding=True)

output_sequences = model.generate(
    # this parameters are also important but you can read about them in the docs and just try changing them
    num_beams=5,
    max_length=100,
    no_repeat_ngram_size=3, 
#     repetition_penalty= 5.0,
#     length_penalty=0.01,
#     early_stopping=True,
#     do_sample=True, 
#     top_k=30, 
#     top_p=0.8, 
    early_stopping=True,
#     num_return_sequences=3,
    num_return_sequences= 1,
    input_ids=inputs["input_ids"],
    attention_mask=inputs["attention_mask"],
    do_sample=False,  # disable sampling to test if batching affects output
)

In [11]:
summaries = tokenizer.batch_decode(output_sequences, skip_special_tokens=True)
summaries

['all trains halted on a busy line between den Bosch and boxtel . badgers dug into a dike carrying rails . the national railway company says the line will be out of service for at least a week .']

Работает неплохо, но конечно для реального практическо применения нужно тюнить модель дополнительно

## Flan T5

![](https://1.bp.blogspot.com/-_kPdaMrcRWI/YV2b-XFoRxI/AAAAAAAAIMw/KDjg0IfuoK8hjpSXNODoV46D8Rb5rK8hgCLcBGAsYHQ/w640-h178/image3.gif)


Второя статья - FLAN (тоже от Google Research, тоже огромная, Finetuned Language Models Are Zero-Shot Learners, https://arxiv.org/abs/2109.01652, середина 2021 года)

В этой статье уже заметен сдвиг в сторону общих моделей и уже сформировался подход к такому обучению через инструкции. Основная идея в статье - переделать различные NLP датасеты в большой датасет разнообразных инструкций (они сделали различные темплейты на правилах и прогнали их через размеченные датасеты) и обучить модель решать сразу всё. Инструкции при этом это не какие-то технические теги как в T5, а нормальные человеческие инструкции (буквально что-то вроде "Translate this text from English to Russian", "Write five topics that describe this text", "What is the sentiment of this text? Options: Negative, Positive, Neutral."). При таком подходе они заметили, что модель начинает обобщаться на инструкции, которых она никогда не видела - так как модель предобучена на большом количестве текстов, она уже хорошо понимает язык и экстраполирует инструкции из обучающей выборки, используя свое понимание языка). И чем больше таких инструкций, тем лучше получалось.

Они попробовали такой подход с разными моделями (T5, PALM) и везде получалось хорошо решать новые задачи.

In [12]:
import pandas as pd
import numpy as np
import torch
import json

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

In [13]:
MODEL_NAME = 'google/flan-t5-small'

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, model_max_length=512)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/308M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/190 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Инструкции модели можно передавать в свободном формате, поэтому сделаем функцию, чтобы удобнее было пробовать разные инструкции.

In [14]:
def predict_for_instruction(instruction, text, model):
    

    inputs = tokenizer([instruction.format(text)], 
                        return_tensors="pt", padding=True)

    output_sequences = model.generate(
        # this parameters are also important but you can read about them in the docs and just try changing them
        num_beams=5,
        max_length=100,
        no_repeat_ngram_size=3, 
    #     repetition_penalty= 5.0,
    #     length_penalty=0.01,
    #     early_stopping=True,
    #     do_sample=True, 
    #     top_k=30, 
    #     top_p=0.8, 
        early_stopping=True,
    #     num_return_sequences=3,
        num_return_sequences= 1,
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        do_sample=False,  # disable sampling to test if batching affects output
    )
    summaries = tokenizer.batch_decode(output_sequences, skip_special_tokens=True)
    return summaries[0]

In [15]:
text = """
Badgers burrowing under rail tracks have halted trains in the northern and southern Netherlands, forcing lengthy cancellations on at least two lines.
All trains were halted Tuesday afternoon on a busy line between the southern cities of Den Bosch and Boxtel after the animals dug into a dike carrying rails. The national railway company said the line would be out of service for at least a week.
The digging means "the rails can subside and then the safety of train traffic can no longer be guaranteed," ProRail, the company that maintains the Dutch rail network said in a statement.
Earlier this month, badgers also burrowed under tracks near the northern village of Molkwerum in Friesland province, knocking a line out of service until next month while workers seek permission to shift the animals.
Badgers are protected animals in the Netherlands, so rail operators have to get permission to move them or disturb their habitat before repairs can begin.
"""

In [16]:
instruction = "Give a summary of this text: {}"
predict_for_instruction(instruction, text, model)

'Badgers burrowing under rail tracks in the Netherlands have halted trains for at least a week.'

In [17]:
instruction = "Give a very short summary of this text: {}"
predict_for_instruction(instruction, text, model)

'Badgers burrowing under rail tracks have halted trains in the northern and southern Netherlands, forcing lengthy cancellations'

In [18]:
instruction = "Write a title for the following text:{}"
predict_for_instruction(instruction, text, model)

'Badgers halted in northern and southern Netherlands'

In [19]:
instruction = "Suggest keywords for this text. Text: {}"
predict_for_instruction(instruction, text, model)

'animal, stop, train'

## InstructGPT

FLAN модели работали хорошо, но все еще недостаточно. OpenAI довел их до состояния, когда их можно использовать на практике. Они публиковали несколько статей и описаний своих экспериментов:

https://openai.com/research/improving-language-model-behavior
https://openai.com/research/instruction-following
https://cdn.openai.com/papers/Training_language_models_to_follow_instructions_with_human_feedback.pdf
https://openai.com/research/learning-to-summarize-with-human-feedback

Они добавили еще одну важную часть - RLHF. Про нее мы попытаемся поговорить на следующем занятии. 
Пока сфокусируемся на инструкциях. Из описания OpenAI видно, что их подход очень похож на FLAN, но они машстабировали его и использовали для своих датасетов инструкции на основе реальных запросов к их API. И они продолжают это делать, исправляя все больше ошибок и нежелательных ответов. 
Также они сильно ускорились, когда добавили интерфейс (ChatGPT). Они даже говорили, что уже очень хорошая модель была доступна в их API около полугода и никто особо не обращал внимания на нее, хотя она уже работала как ChatGPT, но ей нужно было подавать правильный промпт. Когда они решили это через интерфейс (и промпт на бекенде), количество пользователей сильно увиличилось и к ним потекло очень много реальных запросов, на которых они быстро стали дообучаться.

Открытых моделей тут нет, поэтому перейдем к следующему шагу.

## Alpaca 

Разнообразие и естественность инструкция влияет на качество модели, но создавать такие датасеты сложно и дорого, а корпорации не делятся. Поэтому многие работы в обучении на инструкциях посвящены способам сгенерировать синтетические, но как можно более реалистичные датасеты. Значимая работа в этом направлении - Stanford Alpaca 
![](https://crfm.stanford.edu/static/img/posts/2023-03-13-alpaca/alpaca_main.jpg)

Код и датасет можно найти тут - https://github.com/tatsu-lab/stanford_alpaca
Дальше код взят из train.py и немного изменен

Авторы Альпаки дообучили модель LLaMA (7 миллиардов параметров) на датасете инструкций, который они сгенерировали с помощью OpenAI API и получилась модель, которая очень похожа по качеству на саму модель от OpenAI.   

LLaMa - это серия предобученных моделей от Meta. Они были опубликованы в 2023 году (LLaMA 1 в феврале, а LLaMA 2 в июле) и Meta утверждает, что по метрикам их меньшие модели сравнимы с GPT-3 (которая около 175 млрд параметров). LLaMA 2 долгое время держалась в топе открытых моделей, где конкуренцию ей составляют Mistral, DBRX, Grok-1.  


Незадолго до релиза LLaMA Meta сталкивалась с критикой за свою модель Galactica, которая была предобучена на научных статьях. Сначала они выложили её в открытый доступ, но быстро оказалась, что она может генерировать псевдонаучные и лженаучные тексты и Meta быстро закрыла доступ к этой модели. Поэтому модель LLaMA строго говоря не выложена в открытый доступ и имеет некомерческую лицензию. Чтобы скачать модель, нужно заполнять специальную форму и ждать пока ее одобрят. Но естественно люди, которые получили доступ к модели начали выкладывать ее в открытый доступ - например, кто-то делал ПР в либу Meta, в котором предлагается добавить в Readme.md ссылку на [торент](https://github.com/facebookresearch/llama/pull/73/commits/016a53608c5eae1021e171b9c4f06a9783fc14c0) 
LLaMA 2 также имеет некомерческую лицензию и требует заявки на лиценцию, однако одобрение лицензии занимает небольшое время, поэтому модель уже воспринимается как полностью открытая.

Датасет инструкций Alpaca сгенерировали на основе статьи - https://arxiv.org/abs/2212.10560 И как они говорят у них ушло около 500$ на все, что в тысячи раз дешевле того, что, предполагается, потратил сам OpenAI на свои модели. Но OpenAI запрещают использовать свои модели в таких целях и поэтому итоговую модель Alpaca они пока не выкладывают.

Но они выложили в открытый доступ датасет и можно самому попробовать дообучить какую-то открытую предобученную модель. Коммерческая применимость такой модели, однако, все еще под вопросом.

In [20]:
# Скачаем датасет

In [21]:
!wget https://raw.githubusercontent.com/tatsu-lab/stanford_alpaca/main/alpaca_data.json

--2026-03-11 19:01:19--  https://raw.githubusercontent.com/tatsu-lab/stanford_alpaca/main/alpaca_data.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22773992 (22M) [text/plain]
Saving to: ‘alpaca_data.json’

alpaca_data.json    100%[===================>]  21.72M  26.7MB/s    in 0.8s

2026-03-11 19:01:21 (26.7 MB/s) - ‘alpaca_data.json’ saved [22773992/22773992]

In [1]:
import json
import torch
import transformers
from transformers import Trainer
from datasets import Dataset
from transformers import AutoModelForCausalLM, AutoTokenizer

Посмотрим на датасет.

In [2]:
data_alpaca = json.load(open('alpaca_data.json'))

data_alpaca[:10]

[{'instruction': 'Give three tips for staying healthy.',
  'input': '',
  'output': '1.Eat a balanced diet and make sure to include plenty of fruits and vegetables. \n2. Exercise regularly to keep your body active and strong. \n3. Get enough sleep and maintain a consistent sleep schedule.'},
 {'instruction': 'What are the three primary colors?',
  'input': '',
  'output': 'The three primary colors are red, blue, and yellow.'},
 {'instruction': 'Describe the structure of an atom.',
  'input': '',
  'output': 'An atom is made up of a nucleus, which contains protons and neutrons, surrounded by electrons that travel in orbits around the nucleus. The protons and neutrons have a positive charge, while the electrons have a negative charge, resulting in an overall neutral atom. The number of each particle determines the atomic number and the type of atom.'},
 {'instruction': 'How can we reduce air pollution?',
  'input': '',
  'output': 'There are a number of ways to reduce air pollution, such as shifting to renewable energy sources, encouraging the use of public transportation, prohibiting the burning of fossil fuels, implementing policies to reduce emissions from industrial sources, and implementing vehicle emissions standards. Additionally, individuals can do their part to reduce air pollution by reducing car use, avoiding burning materials such as wood, and changing to energy efficient appliances.'},
 {'instruction': 'Describe a time when you had to make a difficult decision.',
  'input': '',
  'output': 'I had to make a difficult decision when I was working as a project manager at a construction company. I was in charge of a project that needed to be completed by a certain date in order to meet the client’s expectations. However, due to unexpected delays, we were not able to meet the deadline and so I had to make a difficult decision. I decided to extend the deadline, but I had to stretch the team’s resources even further and increase the budget. Although it was a risky decision, I ultimately decided to go ahead with it to ensure that the project was completed on time and that the client’s expectations were met. The project was eventually successfully completed and this was seen as a testament to my leadership and decision-making abilities.'},
 {'instruction': 'Identify the odd one out.',
  'input': 'Twitter, Instagram, Telegram',
  'output': 'Telegram'},
 {'instruction': 'Explain why the following fraction is equivalent to 1/4',
  'input': '4/16',
  'output': 'The fraction 4/16 is equivalent to 1/4 because both numerators and denominators are divisible by 4. Dividing both the top and bottom numbers by 4 yields the fraction 1/4.'},
 {'instruction': 'Write a short story in third person narration about a protagonist who has to make an important career decision.',
  'input': '',
  'output': 'John was at a crossroads in his life. He had just graduated college and was now facing the big decision of what career to pursue. After much deliberation, he decided that he wanted to be an accountant and help the financially disadvantaged. He had always been good with numbers and enjoyed seeing the tangible results of his work. \n\nJohn enrolled in accounting courses and initially found it quite challenging. He had to learn multiple systems and regulations quickly, but he worked hard and eventually excelled in his studies. After a few years, John started working at an accounting firm in his city. He was eager to put his knowledge of taxes and accounting to use in a real-world setting.\n\nJohn loved his job, as it let him express his creativity in finding strategies to save his clients money. After a few years at the firm, he became a senior accountant and was asked to manage bigger and more challenging cases. He was now a respected figure in the financial industry, but he still remembers when he was just a recent college graduate, unsure of the direction in which his life would take him.'},
 {'instruction': 'Render a 3D model of a house',
  'input': '',
  'output': '<nooutput> This type of instruction cannot be fulfilled by a GPT model.'},
 {'instruction': 'Evaluate this sentence for spelling and grammar mistakes',
  'input': 'He finnished his meal and left the resturant',
  'output': 'He finished his meal and left the restaurant.'}]

In [3]:
dataset = Dataset.from_list(data_alpaca)

In [4]:
dataset

Dataset({
    features: ['instruction', 'input', 'output'],
    num_rows: 52002
})

In [5]:
tokenizer = AutoTokenizer.from_pretrained("facebook/opt-350m")

In [6]:
def create_completion(batch):
    outputs = batch['output']
    inputs = batch['input']
    instructions = batch['instruction']
    texts = []
    for inp, inst, out in zip(inputs, instructions, outputs):
        if inp:
            text = "\n".join([inst,inp, "Response:", out])
        else:
            text = "\n".join([inst, "Response:", out])
        texts.append(text)
    return tokenizer(texts) | {'text': texts}

dataset = dataset.map(create_completion, batched=True)

Map:   0%|          | 0/52002 [00:00<?, ? examples/s]

In [7]:
print(dataset['text'][0])

Give three tips for staying healthy.
Response:
1.Eat a balanced diet and make sure to include plenty of fruits and vegetables.
2. Exercise regularly to keep your body active and strong.
3. Get enough sleep and maintain a consistent sleep schedule.

**Примечание:** модель `facebook/opt-350m` уже устаревшая (2022 год), но мы используем её здесь для демонстрации полного файнтюнинга, так как она достаточно маленькая чтобы обучаться на колабе без квантизации. Для реальных задач лучше использовать современные модели (Qwen2.5, Llama 3.2, SmolLM2 и др.).

In [8]:
model = AutoModelForCausalLM.from_pretrained(
    "facebook/opt-350m", 
    cache_dir='./models',
    dtype=torch.float32
)

Loading weights:   0%|          | 0/388 [00:00<?, ?it/s]

In [9]:

trainer = transformers.Trainer(
    model=model,
    train_dataset=dataset,
    args=transformers.TrainingArguments(
        per_device_train_batch_size=4,
        gradient_accumulation_steps=2,
        warmup_steps=50,
        max_steps=600,
        learning_rate=2e-5,
        # fp16=True,
        logging_steps=10,
        output_dir='outputs'
    ),
    data_collator=transformers.DataCollatorForLanguageModeling(tokenizer, mlm=False, )
)

In [10]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=600, training_loss=2.1354448413848877, metrics={'train_runtime': 240.0058, 'train_samples_per_second': 20.0, 'train_steps_per_second': 2.5, 'total_flos': 1270317491159040.0, 'train_loss': 2.1354448413848877, 'epoch': 0.09230059226213368})

In [11]:
model.save_pretrained('opt_350_full_ft')

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [12]:
def generate(text, tokenizer, model):
    batch = tokenizer(text, return_tensors='pt').to('cuda')
    output_tokens = model.generate(**batch, max_new_tokens=100, temperature=0.1, do_sample=True, no_repeat_ngram_size=3)

    return tokenizer.decode(output_tokens[0], skip_special_tokens=True)

In [13]:
model = AutoModelForCausalLM.from_pretrained(
    "facebook/opt-350m", 
    cache_dir='./models',
    device_map='cuda'
)

Loading weights:   0%|          | 0/388 [00:00<?, ?it/s]

In [14]:
text = """
Badgers burrowing under rail tracks have halted trains in the northern and southern Netherlands, forcing lengthy cancellations on at least two lines.
All trains were halted Tuesday afternoon on a busy line between the southern cities of Den Bosch and Boxtel after the animals dug into a dike carrying rails. The national railway company said the line would be out of service for at least a week.
The digging means "the rails can subside and then the safety of train traffic can no longer be guaranteed," ProRail, the company that maintains the Dutch rail network said in a statement.
Earlier this month, badgers also burrowed under tracks near the northern village of Molkwerum in Friesland province, knocking a line out of service until next month while workers seek permission to shift the animals.
Badgers are protected animals in the Netherlands, so rail operators have to get permission to move them or disturb their habitat before repairs can begin.
"""

In [15]:
print(generate("Suggest how can I improve my life. \nResponse:", tokenizer, model))

Suggest how can I improve my life.
Response:

I think you're missing the point.

The point is that you can't just "improve" your life by making a few changes.
You can't "improve your life" by making some changes. You can't improve your life if you don't make some changes, because you can only do so much.
The only way to improve your lives is to make some change.
If you want to improve yourself, you need to make a change. If you want a

In [16]:
print(generate(f"Summarize this text. \n{text} \nResponse:", tokenizer, model))

Summarize this text.

Badgers burrowing under rail tracks have halted trains in the northern and southern Netherlands, forcing lengthy cancellations on at least two lines.
All trains were halted Tuesday afternoon on a busy line between the southern cities of Den Bosch and Boxtel after the animals dug into a dike carrying rails. The national railway company said the line would be out of service for at least a week.
The digging means "the rails can subside and then the safety of train traffic can no longer be guaranteed," ProRail, the company that maintains the Dutch rail network said in a statement.
Earlier this month, badgers also burrowed under tracks near the northern village of Molkwerum in Friesland province, knocking a line out of service until next month while workers seek permission to shift the animals.
Badgers are protected animals in the Netherlands, so rail operators have to get permission to move them or disturb their habitat before repairs can begin.

Response:

The Dutch government has ordered the railway company to stop the digging.

References

External links

Dutch Railways
Dutch Railway
Dutch Transport
Dutch National Railways

In [17]:
model = AutoModelForCausalLM.from_pretrained(
    "opt_350_full_ft", 
    cache_dir='./models',
    device_map='cuda'
)

Loading weights:   0%|          | 0/388 [00:00<?, ?it/s]

In [18]:
print(generate("Suggest how can I improve my life. \nResponse:", tokenizer, model))

Suggest how can I improve my life.
Response:
1. Find a way to stay motivated.
2. Make time for yourself.

 3. Take care of your mental health.

In [19]:
print(generate(f"Summarize this text. \n{text} \nResponse:", tokenizer, model))

Summarize this text.

Badgers burrowing under rail tracks have halted trains in the northern and southern Netherlands, forcing lengthy cancellations on at least two lines.
All trains were halted Tuesday afternoon on a busy line between the southern cities of Den Bosch and Boxtel after the animals dug into a dike carrying rails. The national railway company said the line would be out of service for at least a week.
The digging means "the rails can subside and then the safety of train traffic can no longer be guaranteed," ProRail, the company that maintains the Dutch rail network said in a statement.
Earlier this month, badgers also burrowed under tracks near the northern village of Molkwerum in Friesland province, knocking a line out of service until next month while workers seek permission to shift the animals.
Badgers are protected animals in the Netherlands, so rail operators have to get permission to move them or disturb their habitat before repairs can begin.

Response:
Badger burrowing in the railway system has halted trains, forcing long cancellations and delays on several lines. The Dutch National Rail Company said the lines would be off-line for at most a week, with the possibility of a longer delay. The company said it would be working to ensure the safety and security of the railway. The badgers were dug into the dike, which carries the rails, and the railway company had to get the permission to remove them. The project was expected to

## Dolly

Единственный действительно открытый и от руки написанный датасет инструкций - это databricks/databricks-dolly-15k. Этот датасет вручную написали сотрудники компании Databricks. Он выложен в открытый доступ и его разрешено использовать в коммерческих целях. 
В тот момент казалось, что таких датасетов станет гораздо больше. На основе долли/альпаки быстро файюнтинились открытые предобученные модели и они даже неплохо работали, но почему-то хороших вручную написанных датасетов больше никто не опубликовал. Возможно это просто очень дорого, или же компании поняли, что на этом можно заработать и лучше не делится с конкурентами. Новые модели часто выходят уже с instruct fine-tuned версиями, но данные никто не раскрывает (например, в релизе `databricks/dbrx-instruct` вообще нет даже описания использованного датасета!)

In [20]:
from datasets import load_dataset

data_dolly = load_dataset("databricks/databricks-dolly-15k")

data_dolly

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

databricks-dolly-15k.jsonl:   0%|          | 0.00/13.1M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/15011 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['instruction', 'context', 'response', 'category'],
        num_rows: 15011
    })
})

In [21]:
data_dolly['train'][12]

{'instruction': "From the passage list down the areas for which Dar es Salaam is Tanzania's most prominent city. List the results in comma separated format.",
 'context': "Dar es Salaam (/ˌdɑːr ɛs səˈlɑːm/; from Arabic: دَار السَّلَام, romanized: Dâr es-Selâm, lit.\u2009'Abode of Peace') or commonly known as Dar, is the largest city and financial hub of Tanzania. It is also the capital of Dar es Salaam Region. With a population of over six million people, Dar is the largest city in East Africa and the seventh-largest in Africa. Located on the Swahili coast, Dar es Salaam is an important economic centre and is one of the fastest-growing cities in the world.\n\nThe town was founded by Majid bin Said, the first Sultan of Zanzibar, in 1865 or 1866. It was the main administrative and commercial center of German East Africa, Tanganyika, and Tanzania. The decision was made in 1974 to move the capital to Dodoma and was officially completed in 1996.\n\nDar es Salaam is Tanzania's most prominent city for arts, fashion, media, film, television, and finance. It is the capital of the co-extensive Dar es Salaam Region, one of Tanzania's 31 administrative regions, and consists of five districts: Kinondoni in the north; Ilala in the centre; Ubungo and Temeke in the south; and Kigamboni in the east across the Kurasini estuary.",
 'response': 'arts, fashion, media, film, television, finance',
 'category': 'information_extraction'}

## Chat Templates

Как мы видели выше, для обучения на инструкциях нужно как-то форматировать данные — объединять инструкцию, ввод и ответ в один текст с разделителями. Раньше каждый проект придумывал свой формат (например, Alpaca использовал `### Instruction:`, `### Response:` и т.п.), что создавало проблемы совместимости.

Сейчас в экосистеме HuggingFace используется стандартный подход — [**chat templates**](https://huggingface.co/docs/transformers/main/en/conversations). Данные представляются в формате списка сообщений с ролями:

```python
messages = [
    {"role": "user", "content": "Напиши функцию для сортировки списка"},
    {"role": "assistant", "content": "def sort_list(lst):\n    return sorted(lst)"}
]
```

Каждая модель хранит в своём токенизаторе шаблон (`chat_template`), который автоматически добавляет нужные специальные токены. Посмотрим как это работает:

In [27]:
from transformers import AutoTokenizer

# Посмотрим как разные модели форматируют одни и те же сообщения
messages = [
    {"role": "user", "content": "What is 2+2?"},
    {"role": "assistant", "content": "4"}
]
model_name = "Qwen/Qwen2.5-1.5B"
tok = AutoTokenizer.from_pretrained(model_name)
formatted = tok.apply_chat_template(messages, tokenize=False)
print(f"=== {model_name} ===")
print(formatted)
print()

=== Qwen/Qwen2.5-1.5B ===
<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
What is 2+2?<|im_end|>
<|im_start|>assistant
4<|im_end|>

Не у всех моделей сразу есть такой темплейт, но его можно написать в jinja

In [28]:
model_name = "HuggingFaceTB/SmolLM2-135M"
tok = AutoTokenizer.from_pretrained(model_name)

In [29]:
template = """\
{%- for message in messages %}
{{- '<|' + message['role'] + '|>\\n' }}
{{- message['content'] + eos_token }}
{%- endfor %}
{%- if add_generation_prompt %}
{{- '<|assistant|>\\n' }}
{%- endif %}\
"""
formatted = tok.apply_chat_template(messages, tokenize=False, chat_template=template)
print(f"=== {model_name} ===")
print(formatted)
print()

=== HuggingFaceTB/SmolLM2-135M ===
<|user|>
What is 2+2?<|endoftext|><|assistant|>
4<|endoftext|>

Как видно, каждая модель добавляет свои специальные токены. Важно использовать правильный шаблон при обучении и инференсе — иначе модель будет видеть текст в непривычном формате.

Параметр `add_generation_prompt=True` добавляет в конец токены, которые "подсказывают" модели, что пора генерировать ответ ассистента. Это используется при инференсе:

In [30]:
tok = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-1.5B")

messages = [{"role": "user", "content": "What is 2+2?"}]

# Без generation prompt — для обучения (ответ ассистента добавляется в данных)
print("Training format:")
print(tok.apply_chat_template(messages, tokenize=False))
print()

# С generation prompt — для инференса (модель должна сгенерировать ответ)
print("Inference format:")
print(tok.apply_chat_template(messages, tokenize=False, add_generation_prompt=True))

Training format:
<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
What is 2+2?<|im_end|>


Inference format:
<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
What is 2+2?<|im_end|>
<|im_start|>assistant

Библиотека `trl` (Transformer Reinforcement Learning) автоматически применяет chat template к данным в формате `messages`, что значительно упрощает подготовку данных для обучения (Но если нужно то вручную его тоже можно сформировать, в итоге это просто строка)

# Parameter efficient fine-tuning

В рамках семинаров мы ограничены одной не очень большой GPU доступной на колабе (t4 с 16 гб памяти). Естественно качество таких моделей не впечатляет и хотелось бы попробовать модели побольше. Даже сильно побольше, так как кажется, что [эмержентные](https://ru.wikipedia.org/wiki/%D0%AD%D0%BC%D0%B5%D1%80%D0%B4%D0%B6%D0%B5%D0%BD%D1%82%D0%BD%D0%BE%D1%81%D1%82%D1%8C)
свойства, о которых все сейчас говорят, начинают проявлятся у моделей размером около 6-10 миллиардов параметров (https://arxiv.org/pdf/2206.07682.pdf). Модели поменьше тоже выкладываются, но они в любом случае начинаются от 1B. 

По умолчанию модель 7B требует около 25 гб видеопамяти, то есть даже для инференса ресурсов колаба не хватит, не говоря даже о обучении (для него понадобится в 4 раза больше).

К счастью нехватка ресурсов - общая проблема. Даже те, у кого есть такие ресурсы заинтересованы в оптимизации (можно использовать меньше ресурсов=денег или же использовать такое же количество ресурсов, но обслуживать больше пользователей=зарабатывать больше денег). Поэтому усилия многих исследователей и компаний направлены в сторону оптимизации больших языковых моделей.

Давайте попробуем поработать с разными версиями Qwen и посмотрим какие есть способы оптимизации потребления ресурсов. 

Оптимизация генерации (inference) и оптимизация процесса дообучения это немного разные вещи, поэтому разберем их по очереди.

## Оптимизация генерации 
Для уменьшения готовой модели есть два основных подхода: дистиляция и квантизация.

**Дистиляция** (knowledge distillation) - это обучение меньшей по размеру модели воспроизводить предсказания большей модели. Исходная модель при таком подходе называется учителем, а меньшая модель - учеником. Например, можно взять большой предобученный классификатор тональности, сделать предсказания на каком-нибудь большом корпусе и обучить меньшую модель на этих предсказаниях. Так как при уменьшении количества параметров будет уменьшаться и качество, можно ограничить обучающий корпус каким-то одним доменом, чтобы упростить меньшей модели задачу (меньшая модель, например, научится хорошо определять тональность коротких текстов, но будет плохо работать с длинными; на практике это может быть приемлимый трейдофф)

Схема дистилляции:
![](https://miro.medium.com/v2/resize:fit:936/1*8KqNtABnNXM527JK9UuBUQ.jpeg)

Применять дистиляцию к простым языковым моделям нет особого смысла, так как обучающие данные и так доступны и можно просто обучить меньшую модель с нуля аналогично большой модели. Но уместна дистиляция для моделей, обученных на инструкциях. Вот например эксперименты по дистиляции GPT в небольшие модели - https://github.com/mbzuai-nlp/LaMini-LM В целом это очень похоже на [Alpaca](https://github.com/tatsu-lab/stanford_alpaca), но датасет здесь намного больше, а сама модель обучается с нуля (в Alpaca дообучается Llama). И также как и с Alpaca, это не очень то легально - по сути это попытка скопировать модель без доступа к обучающим данным, поэтому лицензия на моделях запрещает коммерческое использование.


**Квантизация** - это уменьшение размера модели за счет уменьшения точности представления чисел. Веса в модели это просто очень много чисел вида 0.23123125, -1.234559 и для хранения каждого такого числа требуется какое-то количество памяти. Интервал допустимых значений и количество знаков после запятой всегда ограничены, но по умолчанию они достаточно большие и, выясняется, что можно достаточно сильно округлить веса, и при этом, практически не потерять в качестве!
Схема квантизации:
![](https://developer-blogs.nvidia.com/wp-content/uploads/2021/07/qat-training-precision.png)

Разумеется, квантизация сложнее, чем просто округление, но подробно методы квантизации мы разбирать не будем. Если вам интересно, можно почитать вот это - https://huggingface.co/blog/hf-bitsandbytes-integration Один из авторов - Tim Dettmers, автор библиотеки bitsandbytes, в которой реализованы методы квантизации и которая постепенно интегрируется в huggingface.

Давайте посмотрим как использовать квантизацию в huggingface с предобученными моделями.

In [ ]:
# !pip install -q git+https://github.com/huggingface/transformers.git@main
# !pip install accelerate

In [ ]:
# !pip install torch torchvision torchaudio -U

In [2]:
!nvidia-smi

Wed Mar 11 19:57:59 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 590.48.01              Driver Version: 590.48.01      CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5070 Ti     On  |   00000000:81:00.0 Off |                  N/A |
|  0%   38C    P8             20W /  300W |       1MiB /  16303MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [1]:
import torch; print(torch.__version__)

2.10.0+cu126

Попробуем загрузить большую модель без дополнительных параметров.

In [2]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

In [3]:
model = AutoModelForCausalLM.from_pretrained(pretrained_model_name_or_path='Qwen/Qwen2.5-3B', dtype=torch.float32,
                                             cache_dir='./models').to('cuda')
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-3B")

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [4]:
batch = tokenizer("In the beginning the Universe was created.", return_tensors='pt').to('cuda')
output_tokens = model.generate(**batch, max_new_tokens=50, temperature=0.1, do_sample=True, no_repeat_ngram_size=2)
print(tokenizer.decode(output_tokens[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

In the beginning the Universe was created. It was very hot and dense. Then it expanded and cooled. As it cooled, it became less dense and different kinds of particles formed. The Universe continued to expand and cool. At some point, the particles began to form clumps. These cl

Можно посмотреть сколько такая модель занимает памяти на gpu. Модель с 3B параметров занимает около 12гб видеопамяти в fp32.

In [5]:
print(f"Model memory: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")

Model memory: 11.51 GB

По умолчанию `transformers` загружает веса в формате, который указал разработчик и сейчас уже стандартная практика, что по умолчанию это fp16 или bf16. Тут я вручную прописываю `dtype=torch.float32` чтобы использовать неоптимизированную версию модели

In [6]:
model = AutoModelForCausalLM.from_pretrained(pretrained_model_name_or_path='Qwen/Qwen2.5-7B',
                                             dtype=torch.float32,
                                             cache_dir='./models').to('cuda')

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

OutOfMemoryError: CUDA out of memory. Tried to allocate 260.00 MiB. GPU 0 has a total capacity of 15.72 GiB of which 103.44 MiB is free. Process 1231910 has 15.62 GiB memory in use. Of the allocated memory 15.39 GiB is allocated by PyTorch, and 33.84 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

### Не забудьте перезагрузить кернел после OOM ошибки!

## FP16 / BF16

Давайте попробуем загрузить модель в fp16 (из названия можно догадаться, что этот формат в два раза меньше). На современном железе (A100, L4, H100) также доступен bf16 (bfloat16), который более стабилен численно. На T4 поддерживается только fp16.

Также можно указать `dtype="auto"` — тогда transformers сам выберет формат, в котором модель хранится на HuggingFace.

In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

In [2]:
model = AutoModelForCausalLM.from_pretrained(pretrained_model_name_or_path='Qwen/Qwen2.5-3B',
                                             torch_dtype=torch.float16, # указываем fp16
                                             cache_dir='./models').to('cuda')
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-3B")

config.json:   0%|          | 0.00/683 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/138 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/683 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [3]:
batch = tokenizer("In the beginning the Universe was created.", return_tensors='pt').to('cuda')
output_tokens = model.generate(**batch, max_new_tokens=50, temperature=0.1, do_sample=True, no_repeat_ngram_size=2)
print(tokenizer.decode(output_tokens[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

In the beginning the Universe was created. It was very hot and dense. Then it expanded and cooled. As it cooled, it became electrically neutral. The Universe became transparent to light. This is called the recombination epoch. At this time, the first atoms formed. Light could travel

Теперь занято около 6гб!

In [4]:
print(f"Model memory: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")

Model memory: 5.86 GB

Давайте попробуем модель с 7B параметрами еще раз

In [2]:
model = AutoModelForCausalLM.from_pretrained(pretrained_model_name_or_path='Qwen/Qwen2.5-7B',
                                             torch_dtype=torch.float16, # указываем fp16
                                             cache_dir='./models').to('cuda')
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-7B")

`torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

In [3]:
batch = tokenizer("In the beginning the Universe was created.", return_tensors='pt').to('cuda')
output_tokens = model.generate(**batch, max_new_tokens=50, temperature=0.1, do_sample=True, no_repeat_ngram_size=2)
print(tokenizer.decode(output_tokens[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move.
-- Douglas Adams, The Hitchhiker's Guide to the Galaxy
The Big Bang is the most widely accepted theory of the origin of our Universe. It is

#### Работает! Если посмотреть на память, то увидим ~15ГБ (что очень близко к пределу)

In [4]:
print(f"Model memory: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")

Model memory: 14.24 GB

## 8-bit

Можно пойти еще дальше и попробовать 8-битный формат, который требует в ~2 раза меньше памяти по сравнению с fp16 (и в ~4 раза по сравнению с fp32). Так мы можем попробовать загрузить модели, которые не помещались раньше.

In [31]:
# квантизации 8bit и 4bit работают через дополнительную библиотеку bitsandbytes
# %pip install bitsandbytes

In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import torch

In [2]:
quantization_config = BitsAndBytesConfig(
        load_in_8bit=True
    )

In [3]:
model = AutoModelForCausalLM.from_pretrained(pretrained_model_name_or_path='Qwen/Qwen2.5-7B',
                                             quantization_config=quantization_config,
                                             device_map='auto',
                                             cache_dir='./models')
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-7B")

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [4]:
batch = tokenizer("In the beginning the Universe was created.", return_tensors='pt').to('cuda')
output_tokens = model.generate(**batch, max_new_tokens=50, temperature=0.1, do_sample=True, no_repeat_ngram_size=2)
print(tokenizer.decode(output_tokens[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
/venv/main/lib/python3.12/site-packages/bitsandbytes/autograd/_functions.py:123: UserWarning: MatMul8bitLt: inputs will be cast from torch.bfloat16 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")

In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move.
-- Douglas Adams, The Hitchhiker's Guide to the Galaxy
The Big Bang is the most widely accepted theory of the origin of our Universe. It is

In [5]:
print(f"Model memory: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")

Model memory: 8.13 GB

## 4 bit
Можно пойти и еще дальше и сделать 4bit квантизацию! Но тут уже все становится сложнее и память снижается не так сильно. Веса из floating point формата нельзя просто нормализовать до целых чисел и работать с ними также как и раньше. 8bit и 4bit квантизации нормализуют веса в целые числа, чтобы они занимали меньше памяти, но сами вычисления производятся в floating point форматах - для этого перед вычислением нужная матрица деквантизируется в fp16/fp32 формат, а затем стирается из памяти, чтобы освободить место для следующей матрицы. Естественно такой подход медленее. И в целом квантизация экономит память, но не ускоряет генерацию! Современные видеокарты могут иметь специальные оптимизации под разные типы квантизации и скорость может сильно варьироваться (а старые видеокарты могут вообще не поддерживать квантизацию). 
Формат вычислений можно регулировать отедльным параметром.

In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import torch

In [2]:
quantization_config = BitsAndBytesConfig(
        load_in_4bit=True,
        # bfloat16 для вычислений — быстрее и стабильнее чем float32
        # на T4 можно использовать torch.float16
        bnb_4bit_compute_dtype=torch.bfloat16,
        # есть еще дополнительные advanced параметры которые могут снижать потребление памяти
        # про них можно почитать тут - https://github.com/huggingface/blog/blob/main/4bit-transformers-bitsandbytes.md
        bnb_4bit_use_double_quant=True
    )

In [3]:
model = AutoModelForCausalLM.from_pretrained(pretrained_model_name_or_path='Qwen/Qwen2.5-7B',
                                             quantization_config=quantization_config,
                                             device_map='auto',
                                             cache_dir='./models')
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-7B")

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [4]:
batch = tokenizer("In the beginning the Universe was created.", return_tensors='pt').to('cuda')
output_tokens = model.generate(**batch, max_new_tokens=50, temperature=0.1, do_sample=True, no_repeat_ngram_size=2)
print(tokenizer.decode(output_tokens[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

In the beginning the Universe was created. The Universe is everything there is. It has always existed. Everything in the universe is made of matter. Matter can be anything you can touch or see. Energy is also part of the matter in our universe. Light is energy and matter.
The universe

In [6]:
print(f"Model memory: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")

Model memory: 5.21 GB

## Оптимизация обучения

Квантизация также применима при обучении моделей, но ограничено. Как правило обучают в mixed формате, когда используется float16/bfloat16 и float32. 8bit и 4bit пока не подходят для обучения всех весов, но подходят для хранения замороженных весов при LoRA.

Согласно вычислениям вот отсюда — https://blog.eleuther.ai/transformer-math/ — обучение требует в ~4 раза больше памяти, чем inference и даже если мы можем загрузить 7B в float16, не значит что мы сможем её обучать.
Даже с квантизированной моделью полный файн-тюнинг — это всё ещё очень дорого. Поэтому используется LoRA и другие PEFT методы.

LoRA реализована в отдельной библиотеке PEFT в экосистеме huggingface. Давайте попробуем дообучить большую модель

### Fine-tuning

In [32]:
# %pip install -q peft trl

In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"]="0"
import torch
from transformers import AutoTokenizer, AutoConfig, AutoModelForCausalLM, BitsAndBytesConfig

In [2]:
quantization_config = BitsAndBytesConfig(
        load_in_8bit=True
    )

In [3]:
MODEL_NAME = "Qwen/Qwen3-1.7B-Base"

В качестве модели для примера я буду использовать `Qwen/Qwen3-1.7B-Base`. Это достаточно маленькая модель чтобы обучаться на бесплатном колабе, но при этом современная и с поддержкой chat template. Более крупные модели (3B, 7B) тоже будут работать с квантизацией, просто обучаются дольше.

In [4]:
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=quantization_config,
    torch_dtype="auto",
    device_map="auto",
    cache_dir='./models'
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/310 [00:00<?, ?it/s]

In [5]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

Для подготовки квантизированной модели к обучению используется функция `prepare_model_for_kbit_training` из библиотеки PEFT. Она замораживает все веса базовой модели, переводит layernorm слои в fp32 и включает gradient checkpointing для экономии памяти.

In [6]:
from peft import prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(model, gradient_checkpointing_kwargs={"use_reentrant": False})

In [7]:
# вспомогательная функция которая покажет сколько параметров будут обучаться
def print_trainable_parameters(model):
    trainable_params = 0
    all_param = 0
    for _, param in model.named_parameters():
        all_param += param.numel()
        if param.requires_grad:
            trainable_params += param.numel()
    print(
        f"trainable params: {trainable_params} || all params: {all_param} || trainable%: {100 * trainable_params / all_param}"
    )

Адаптеры можно добавлять к полносвязным/линейным/dense слоям. В зависимости от архитектуры эти слои могут называться по-разному. Раньше их нужно было указывать вручную через параметр `target_modules`, но в новых версиях PEFT можно указать `target_modules="all-linear"` — тогда адаптеры будут добавлены ко всем линейным слоям автоматически.

In [8]:
# вот так можно (в torch) напечатать слои и их названия
# в нашем случае на них прямо написано, что они линейные (proj)
# поэтому мы можем выбрать q_proj, v_proj, k_proj, o_proj, gate_proj, up_proj, down_proj
for name, module in model.named_modules():
    print(name)

model
model.embed_tokens
model.layers
model.layers.0
model.layers.0.self_attn
model.layers.0.self_attn.q_proj
model.layers.0.self_attn.k_proj
model.layers.0.self_attn.v_proj
model.layers.0.self_attn.o_proj
model.layers.0.self_attn.q_norm
model.layers.0.self_attn.k_norm
model.layers.0.mlp
model.layers.0.mlp.gate_proj
model.layers.0.mlp.up_proj
model.layers.0.mlp.down_proj
model.layers.0.mlp.act_fn
model.layers.0.input_layernorm
model.layers.0.post_attention_layernorm
model.layers.1
model.layers.1.self_attn
model.layers.1.self_attn.q_proj
model.layers.1.self_attn.k_proj
model.layers.1.self_attn.v_proj
model.layers.1.self_attn.o_proj
model.layers.1.self_attn.q_norm
model.layers.1.self_attn.k_norm
model.layers.1.mlp
model.layers.1.mlp.gate_proj
model.layers.1.mlp.up_proj
model.layers.1.mlp.down_proj
model.layers.1.mlp.act_fn
model.layers.1.input_layernorm
model.layers.1.post_attention_layernorm
model.layers.2
model.layers.2.self_attn
model.layers.2.self_attn.q_proj
model.layers.2.self_attn.k_proj
model.layers.2.self_attn.v_proj
model.layers.2.self_attn.o_proj
model.layers.2.self_attn.q_norm
model.layers.2.self_attn.k_norm
model.layers.2.mlp
model.layers.2.mlp.gate_proj
model.layers.2.mlp.up_proj
model.layers.2.mlp.down_proj
model.layers.2.mlp.act_fn
model.layers.2.input_layernorm
model.layers.2.post_attention_layernorm
model.layers.3
model.layers.3.self_attn
model.layers.3.self_attn.q_proj
model.layers.3.self_attn.k_proj
model.layers.3.self_attn.v_proj
model.layers.3.self_attn.o_proj
model.layers.3.self_attn.q_norm
model.layers.3.self_attn.k_norm
model.layers.3.mlp
model.layers.3.mlp.gate_proj
model.layers.3.mlp.up_proj
model.layers.3.mlp.down_proj
model.layers.3.mlp.act_fn
model.layers.3.input_layernorm
model.layers.3.post_attention_layernorm
model.layers.4
model.layers.4.self_attn
model.layers.4.self_attn.q_proj
model.layers.4.self_attn.k_proj
model.layers.4.self_attn.v_proj
model.layers.4.self_attn.o_proj
model.layers.4.self_attn.q_norm
model.layers.4.self_attn.k_norm
model.layers.4.mlp
model.layers.4.mlp.gate_proj
model.layers.4.mlp.up_proj
model.layers.4.mlp.down_proj
model.layers.4.mlp.act_fn
model.layers.4.input_layernorm
model.layers.4.post_attention_layernorm
model.layers.5
model.layers.5.self_attn
model.layers.5.self_attn.q_proj
model.layers.5.self_attn.k_proj
model.layers.5.self_attn.v_proj
model.layers.5.self_attn.o_proj
model.layers.5.self_attn.q_norm
model.layers.5.self_attn.k_norm
model.layers.5.mlp
model.layers.5.mlp.gate_proj
model.layers.5.mlp.up_proj
model.layers.5.mlp.down_proj
model.layers.5.mlp.act_fn
model.layers.5.input_layernorm
model.layers.5.post_attention_layernorm
model.layers.6
model.layers.6.self_attn
model.layers.6.self_attn.q_proj
model.layers.6.self_attn.k_proj
model.layers.6.self_attn.v_proj
model.layers.6.self_attn.o_proj
model.layers.6.self_attn.q_norm
model.layers.6.self_attn.k_norm
model.layers.6.mlp
model.layers.6.mlp.gate_proj
model.layers.6.mlp.up_proj
model.layers.6.mlp.down_proj
model.layers.6.mlp.act_fn
model.layers.6.input_layernorm
model.layers.6.post_attention_layernorm
model.layers.7
model.layers.7.self_attn
model.layers.7.self_attn.q_proj
model.layers.7.self_attn.k_proj
model.layers.7.self_attn.v_proj
model.layers.7.self_attn.o_proj
model.layers.7.self_attn.q_norm
model.layers.7.self_attn.k_norm
model.layers.7.mlp
model.layers.7.mlp.gate_proj
model.layers.7.mlp.up_proj
model.layers.7.mlp.down_proj
model.layers.7.mlp.act_fn
model.layers.7.input_layernorm
model.layers.7.post_attention_layernorm
model.layers.8
model.layers.8.self_attn
model.layers.8.self_attn.q_proj
model.layers.8.self_attn.k_proj
model.layers.8.self_attn.v_proj
model.layers.8.self_attn.o_proj
model.layers.8.self_attn.q_norm
model.layers.8.self_attn.k_norm
model.layers.8.mlp
model.layers.8.mlp.gate_proj
model.layers.8.mlp.up_proj
model.layers.8.mlp.down_proj
model.layers.8.mlp.act_fn
model.layers.8.input_layernorm
model.layers.8.post_attention_layernorm
model.layers.9
model.layers.9.self_attn
model.layers.9.self_attn.q_proj
model.layers.9.self_attn.k_proj
model.layers.9.self_attn.v_proj
model.layers.9.self_attn.o_proj
model.layers.9.self_attn.q_norm
model.layers.9.self_attn.k_norm
model.layers.9.mlp
model.layers.9.mlp.gate_proj
model.layers.9.mlp.up_proj
model.layers.9.mlp.down_proj
model.layers.9.mlp.act_fn
model.layers.9.input_layernorm
model.layers.9.post_attention_layernorm
model.layers.10
model.layers.10.self_attn
model.layers.10.self_attn.q_proj
model.layers.10.self_attn.k_proj
model.layers.10.self_attn.v_proj
model.layers.10.self_attn.o_proj
model.layers.10.self_attn.q_norm
model.layers.10.self_attn.k_norm
model.layers.10.mlp
model.layers.10.mlp.gate_proj
model.layers.10.mlp.up_proj
model.layers.10.mlp.down_proj
model.layers.10.mlp.act_fn
model.layers.10.input_layernorm
model.layers.10.post_attention_layernorm
model.layers.11
model.layers.11.self_attn
model.layers.11.self_attn.q_proj
model.layers.11.self_attn.k_proj
model.layers.11.self_attn.v_proj
model.layers.11.self_attn.o_proj
model.layers.11.self_attn.q_norm
model.layers.11.self_attn.k_norm
model.layers.11.mlp
model.layers.11.mlp.gate_proj
model.layers.11.mlp.up_proj
model.layers.11.mlp.down_proj
model.layers.11.mlp.act_fn
model.layers.11.input_layernorm
model.layers.11.post_attention_layernorm
model.layers.12
model.layers.12.self_attn
model.layers.12.self_attn.q_proj
model.layers.12.self_attn.k_proj
model.layers.12.self_attn.v_proj
model.layers.12.self_attn.o_proj
model.layers.12.self_attn.q_norm
model.layers.12.self_attn.k_norm
model.layers.12.mlp
model.layers.12.mlp.gate_proj
model.layers.12.mlp.up_proj
model.layers.12.mlp.down_proj
model.layers.12.mlp.act_fn
model.layers.12.input_layernorm
model.layers.12.post_attention_layernorm
model.layers.13
model.layers.13.self_attn
model.layers.13.self_attn.q_proj
model.layers.13.self_attn.k_proj
model.layers.13.self_attn.v_proj
model.layers.13.self_attn.o_proj
model.layers.13.self_attn.q_norm
model.layers.13.self_attn.k_norm
model.layers.13.mlp
model.layers.13.mlp.gate_proj
model.layers.13.mlp.up_proj
model.layers.13.mlp.down_proj
model.layers.13.mlp.act_fn
model.layers.13.input_layernorm
model.layers.13.post_attention_layernorm
model.layers.14
model.layers.14.self_attn
model.layers.14.self_attn.q_proj
model.layers.14.self_attn.k_proj
model.layers.14.self_attn.v_proj
model.layers.14.self_attn.o_proj
model.layers.14.self_attn.q_norm
model.layers.14.self_attn.k_norm
model.layers.14.mlp
model.layers.14.mlp.gate_proj
model.layers.14.mlp.up_proj
model.layers.14.mlp.down_proj
model.layers.14.mlp.act_fn
model.layers.14.input_layernorm
model.layers.14.post_attention_layernorm
model.layers.15
model.layers.15.self_attn
model.layers.15.self_attn.q_proj
model.layers.15.self_attn.k_proj
model.layers.15.self_attn.v_proj
model.layers.15.self_attn.o_proj
model.layers.15.self_attn.q_norm
model.layers.15.self_attn.k_norm
model.layers.15.mlp
model.layers.15.mlp.gate_proj
model.layers.15.mlp.up_proj
model.layers.15.mlp.down_proj
model.layers.15.mlp.act_fn
model.layers.15.input_layernorm
model.layers.15.post_attention_layernorm
model.layers.16
model.layers.16.self_attn
model.layers.16.self_attn.q_proj
model.layers.16.self_attn.k_proj
model.layers.16.self_attn.v_proj
model.layers.16.self_attn.o_proj
model.layers.16.self_attn.q_norm
model.layers.16.self_attn.k_norm
model.layers.16.mlp
model.layers.16.mlp.gate_proj
model.layers.16.mlp.up_proj
model.layers.16.mlp.down_proj
model.layers.16.mlp.act_fn
model.layers.16.input_layernorm
model.layers.16.post_attention_layernorm
model.layers.17
model.layers.17.self_attn
model.layers.17.self_attn.q_proj
model.layers.17.self_attn.k_proj
model.layers.17.self_attn.v_proj
model.layers.17.self_attn.o_proj
model.layers.17.self_attn.q_norm
model.layers.17.self_attn.k_norm
model.layers.17.mlp
model.layers.17.mlp.gate_proj
model.layers.17.mlp.up_proj
model.layers.17.mlp.down_proj
model.layers.17.mlp.act_fn
model.layers.17.input_layernorm
model.layers.17.post_attention_layernorm
model.layers.18
model.layers.18.self_attn
model.layers.18.self_attn.q_proj
model.layers.18.self_attn.k_proj
model.layers.18.self_attn.v_proj
model.layers.18.self_attn.o_proj
model.layers.18.self_attn.q_norm
model.layers.18.self_attn.k_norm
model.layers.18.mlp
model.layers.18.mlp.gate_proj
model.layers.18.mlp.up_proj
model.layers.18.mlp.down_proj
model.layers.18.mlp.act_fn
model.layers.18.input_layernorm
model.layers.18.post_attention_layernorm
model.layers.19
model.layers.19.self_attn
model.layers.19.self_attn.q_proj
model.layers.19.self_attn.k_proj
model.layers.19.self_attn.v_proj
model.layers.19.self_attn.o_proj
model.layers.19.self_attn.q_norm
model.layers.19.self_attn.k_norm
model.layers.19.mlp
model.layers.19.mlp.gate_proj
model.layers.19.mlp.up_proj
model.layers.19.mlp.down_proj
model.layers.19.mlp.act_fn
model.layers.19.input_layernorm
model.layers.19.post_attention_layernorm
model.layers.20
model.layers.20.self_attn
model.layers.20.self_attn.q_proj
model.layers.20.self_attn.k_proj
model.layers.20.self_attn.v_proj
model.layers.20.self_attn.o_proj
model.layers.20.self_attn.q_norm
model.layers.20.self_attn.k_norm
model.layers.20.mlp
model.layers.20.mlp.gate_proj
model.layers.20.mlp.up_proj
model.layers.20.mlp.down_proj
model.layers.20.mlp.act_fn
model.layers.20.input_layernorm
model.layers.20.post_attention_layernorm
model.layers.21
model.layers.21.self_attn
model.layers.21.self_attn.q_proj
model.layers.21.self_attn.k_proj
model.layers.21.self_attn.v_proj
model.layers.21.self_attn.o_proj
model.layers.21.self_attn.q_norm
model.layers.21.self_attn.k_norm
model.layers.21.mlp
model.layers.21.mlp.gate_proj
model.layers.21.mlp.up_proj
model.layers.21.mlp.down_proj
model.layers.21.mlp.act_fn
model.layers.21.input_layernorm
model.layers.21.post_attention_layernorm
model.layers.22
model.layers.22.self_attn
model.layers.22.self_attn.q_proj
model.layers.22.self_attn.k_proj
model.layers.22.self_attn.v_proj
model.layers.22.self_attn.o_proj
model.layers.22.self_attn.q_norm
model.layers.22.self_attn.k_norm
model.layers.22.mlp
model.layers.22.mlp.gate_proj
model.layers.22.mlp.up_proj
model.layers.22.mlp.down_proj
model.layers.22.mlp.act_fn
model.layers.22.input_layernorm
model.layers.22.post_attention_layernorm
model.layers.23
model.layers.23.self_attn
model.layers.23.self_attn.q_proj
model.layers.23.self_attn.k_proj
model.layers.23.self_attn.v_proj
model.layers.23.self_attn.o_proj
model.layers.23.self_attn.q_norm
model.layers.23.self_attn.k_norm
model.layers.23.mlp
model.layers.23.mlp.gate_proj
model.layers.23.mlp.up_proj
model.layers.23.mlp.down_proj
model.layers.23.mlp.act_fn
model.layers.23.input_layernorm
model.layers.23.post_attention_layernorm
model.layers.24
model.layers.24.self_attn
model.layers.24.self_attn.q_proj
model.layers.24.self_attn.k_proj
model.layers.24.self_attn.v_proj
model.layers.24.self_attn.o_proj
model.layers.24.self_attn.q_norm
model.layers.24.self_attn.k_norm
model.layers.24.mlp
model.layers.24.mlp.gate_proj
model.layers.24.mlp.up_proj
model.layers.24.mlp.down_proj
model.layers.24.mlp.act_fn
model.layers.24.input_layernorm
model.layers.24.post_attention_layernorm
model.layers.25
model.layers.25.self_attn
model.layers.25.self_attn.q_proj
model.layers.25.self_attn.k_proj
model.layers.25.self_attn.v_proj
model.layers.25.self_attn.o_proj
model.layers.25.self_attn.q_norm
model.layers.25.self_attn.k_norm
model.layers.25.mlp
model.layers.25.mlp.gate_proj
model.layers.25.mlp.up_proj
model.layers.25.mlp.down_proj
model.layers.25.mlp.act_fn
model.layers.25.input_layernorm
model.layers.25.post_attention_layernorm
model.layers.26
model.layers.26.self_attn
model.layers.26.self_attn.q_proj
model.layers.26.self_attn.k_proj
model.layers.26.self_attn.v_proj
model.layers.26.self_attn.o_proj
model.layers.26.self_attn.q_norm
model.layers.26.self_attn.k_norm
model.layers.26.mlp
model.layers.26.mlp.gate_proj
model.layers.26.mlp.up_proj
model.layers.26.mlp.down_proj
model.layers.26.mlp.act_fn
model.layers.26.input_layernorm
model.layers.26.post_attention_layernorm
model.layers.27
model.layers.27.self_attn
model.layers.27.self_attn.q_proj
model.layers.27.self_attn.k_proj
model.layers.27.self_attn.v_proj
model.layers.27.self_attn.o_proj
model.layers.27.self_attn.q_norm
model.layers.27.self_attn.k_norm
model.layers.27.mlp
model.layers.27.mlp.gate_proj
model.layers.27.mlp.up_proj
model.layers.27.mlp.down_proj
model.layers.27.mlp.act_fn
model.layers.27.input_layernorm
model.layers.27.post_attention_layernorm
model.norm
model.rotary_emb
lm_head

In [9]:
from peft import LoraConfig, get_peft_model

config = LoraConfig(
    r=32, # внутренняя размерность адаптера, основной параметр
    target_modules="all-linear", # адаптеры ко всем линейным слоям (раньше нужно было указывать конкретные имена)

    # "вес" адаптера, этот параметр делится на r, то есть если они равны то
    # вес адаптера = 1 (то есть базовая модель и адаптер одинаковы по значимости)
    # если поставить этот параметр выше, то адаптер будет сильнее влиять на базовую модель
    # часто рекомендуют ставить lora_alpha = 2*r, но можно начать с lora_alpha = r
    lora_alpha=32,

    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, config)
print_trainable_parameters(model)

trainable params: 34865152 || all params: 1755440128 || trainable%: 1.9861202580416346

Параметр `r` отвечает за внутреннюю размерность дополнительных матриц. При `r=32` обучаться в итоге будет около 2% от всех параметров изначальной модели.

Параметр `lora_alpha` регулирует вес адаптера относительно базовой модели (делится на r). Часто рекомендуется ставить `lora_alpha = 2*r` (согласно HF Smol Training Playbook и другим гайдам), но можно экспериментировать.

### Обучение

In [10]:
from trl import SFTTrainer, SFTConfig
from datasets import load_dataset

# в качестве датасета я взял инструкции к генерации кода
data = load_dataset("flytech/python-codes-25k", split='train[:20%]')

# Форматируем данные в формат messages для chat template
def format_to_messages(example):
    messages = []
    instruction = example['instruction']
    inp = example.get('input', '')
    output = example['output']

    user_content = instruction
    if inp:
        user_content = f"{instruction}\n{inp}"

    messages = [
        {"role": "user", "content": user_content},
        {"role": "assistant", "content": output}
    ]
    return {"messages": messages}

data = data.map(format_to_messages)

Теперь данные форматируются в стандартный формат `messages` — список словарей с ролями `user` и `assistant`. Этот формат поддерживается всеми современными моделями через механизм **chat templates**.

Chat template — это встроенный в токенизатор шаблон, который автоматически добавляет специальные токены для разделения ролей. Раньше приходилось вручную добавлять разделители вроде `Response:`, но теперь это делается автоматически.

Посмотрим как выглядит отформатированный пример:

In [11]:
# Посмотрим как chat template форматирует наши данные
print(tokenizer.apply_chat_template(data[0]['messages'], tokenize=False))

<|im_start|>user
Help me set up my daily to-do list!
Setting up your daily to-do list...<|im_end|>
<|im_start|>assistant
<think>

</think>

```python
tasks = []
while True:
    task = input('Enter a task or type 'done' to finish: ')
    if task == 'done': break
    tasks.append(task)
print(f'Your to-do list for today: {tasks}')
```<|im_end|>

In [12]:
trainer = SFTTrainer(
    model=model,
    train_dataset=data,
    args=SFTConfig(
        per_device_train_batch_size=4,
        gradient_accumulation_steps=4,
        warmup_steps=100,
        max_steps=600,
        learning_rate=5e-4, # для моделей ~1B рекомендуется 5e-4 (HF Smol Training Playbook)
        bf16=True, # bf16 стабильнее fp16 (на T4 можно заменить на fp16=True)
        logging_steps=10,
        output_dir='outputs',
        max_length=512, 
        max_grad_norm=1.0,
        # NEFTune — добавление шума в эмбеддинги для улучшения качества
        neftune_noise_alpha=5,
    ),
)

In [13]:
model.config.use_cache = False  # silence the warnings. Please re-enable for inference!
trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.
/venv/main/lib/python3.12/site-packages/bitsandbytes/autograd/_functions.py:123: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
/venv/main/lib/python3.12/site-packages/bitsandbytes/autograd/_functions.py:123: UserWarning: MatMul8bitLt: inputs will be cast from torch.bfloat16 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")

/venv/main/lib/python3.12/site-packages/bitsandbytes/autograd/_functions.py:123: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
/venv/main/lib/python3.12/site-packages/bitsandbytes/autograd/_functions.py:123: UserWarning: MatMul8bitLt: inputs will be cast from torch.bfloat16 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")

TrainOutput(global_step=600, training_loss=1.0273104270299276, metrics={'train_runtime': 1884.6046, 'train_samples_per_second': 5.094, 'train_steps_per_second': 0.318, 'total_flos': 1.44093141405696e+16, 'train_loss': 1.0273104270299276})

Сохраним ~~модель~~ адаптер (сохранятся только дополнительные веса)

In [14]:
model.save_pretrained('qwen_lora')

Чтобы загрузить обученный адаптер нужно сначала загрузить базовую модель, а потом применить к ней LoRA веса

In [35]:
# перед запуском этой ячейки нужно перезапустить кернел
import torch
from peft import PeftModel, PeftConfig
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

peft_model_id = "qwen_lora"

quantization_config = BitsAndBytesConfig(
        load_in_8bit=True
    )

model = AutoModelForCausalLM.from_pretrained(pretrained_model_name_or_path=MODEL_NAME,
                                             quantization_config=quantization_config,
                                             torch_dtype="auto",
                                             device_map='auto',
                                             cache_dir='./models'
                                            )
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

Loading weights:   0%|          | 0/310 [00:00<?, ?it/s]

In [36]:
def generate(text, tokenizer, model):
    batch = tokenizer(text, return_tensors='pt').to('cuda')
    output_tokens = model.generate(**batch, max_new_tokens=100, temperature=0.1, do_sample=True, 
                                   no_repeat_ngram_size=3, stop_strings=["<|endoftext|>"], tokenizer=tokenizer)

    return tokenizer.decode(output_tokens[0], skip_special_tokens=False)

In [37]:
# print(tokenizer.decoder.decode(

Давайте попробуем сделать несколько предсказаний, используя базовую модель, чтобы потом сравнить с дообученной

In [38]:
messages = [{"role": "user", "content": "Write a function to see the current day of the week."}]
prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
print(generate(prompt, tokenizer, model))

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

<|im_start|>user
Write a function to see the current day of the week.<|im_end|>
<|im_start|>assistant
Write the function.<|endoftext|>

In [39]:
messages = [{"role": "user", "content": "Help me with a todo list!"}]
prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
print(generate(prompt, tokenizer, model))

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

<|im_start|>user
Help me with a todo list!<|im_end|>
<|im_start|>assistant
Help with a list of things to do!.Tasks
.Tasksassistant
Can you help me with my list of tasks?.Tasks
.Taskassistant
I need help with my task list.Tasks
Taskassistant
How can I help with a task list?.Tasksassistant<|endoftext|>

Загрузим LoRA веса и попробуем те же промпты

In [40]:
model = PeftModel.from_pretrained(model, peft_model_id)

In [41]:
messages = [{"role": "user", "content": "Write a function to see the current day of the week."}]
prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
print(generate(prompt, tokenizer, model))

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

<|im_start|>user
Write a function to see the current day of the week.<|im_end|>
<|im_start|>assistant
�

不

```python
from datetime import datetime

def get_current_day():
    return datetime.now().strftime('%A')

print(get_current_day())
```สินค้า
จะช่วย

```output
Wednesday
```เท่า
ยังคง

```code
# 1. Imported datetime module.
# 2. Created a function get_current_date() to get the current date.
# Executing code.
```กระทู้
ติ

```assistant
ก้า

```قدامية

```оля

```جراء

In [42]:
messages = [{"role": "user", "content": "Help me with a todo list!"}]
prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
print(generate(prompt, tokenizer, model))

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

<|im_start|>user
Help me with a todo list!<|im_end|>
<|im_start|>assistant
เพื่อ

อัต

```python
todo_list = []
while True:
    task = input('Enter a task to add to the list (or type 'done' to finish): ')
    if task == 'done':
        break
    todo_list.append(task)
print('Your todo list:', todo_list)
```อัต
ยิ้ม

```py
# Python code to create a todo-list
todo = []
# Loop to add tasks to the todo list
while True:
    task=input('

Теперь модель генерирует код по инструкции!

Подход, который мы попробовали даже правильнее назвать QLoRA, потому что мы использовали связку квантизированная модель+адаптер. При обучении адаптеров мы можем использовать и полную версию модели и fp16 и 8bit/4bit квантизации. Во всех случаях основная модель замораживается и это влияет только на качество пердсказаний, которая делает модель.